In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
parkinsons_telemonitoring = fetch_ucirepo(id=189) 
  
# data (as pandas dataframes) 
X = parkinsons_telemonitoring.data.features 
y = parkinsons_telemonitoring.data.targets 
  
# metadata 
print(parkinsons_telemonitoring.metadata) 
  
# variable information 
print(parkinsons_telemonitoring.variables) 

{'uci_id': 189, 'name': 'Parkinsons Telemonitoring', 'repository_url': 'https://archive.ics.uci.edu/dataset/189/parkinsons+telemonitoring', 'data_url': 'https://archive.ics.uci.edu/static/public/189/data.csv', 'abstract': "Oxford Parkinson's Disease Telemonitoring Dataset", 'area': 'Health and Medicine', 'tasks': ['Regression'], 'characteristics': ['Tabular'], 'num_instances': 5875, 'num_features': 19, 'feature_types': ['Integer', 'Real'], 'demographics': ['Age', 'Sex'], 'target_col': ['motor_UPDRS', 'total_UPDRS'], 'index_col': ['subject#'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2009, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C5ZS3N', 'creators': ['Athanasios Tsanas', 'Max Little'], 'intro_paper': {'title': "Accurate Telemonitoring of Parkinson's Disease Progression by Noninvasive Speech Tests", 'authors': 'A. Tsanas, Max A. Little, P. McSharry, L. Ramig', 'published_in': 'IEEE Transactions on Biomedical Engineering', 

In [18]:
y=y['motor_UPDRS']

In [19]:
import pandas as pd



# 统计每个年龄的人数
age_counts = X['age'].value_counts()
print(age_counts)

# 根据年龄区间拆分数据集
bins = [0,49,60,70,80,100]  # 这里的bins是年龄区间的边界，你可以根据需要进行修改
labels = ["0-49","50-60","60-70","70-80","80+"]  # 这里的labels是每个年龄区间的标签，你可以根据需要进行修改
X['age_group'] = pd.cut(X['age'], bins=bins, labels=labels, right=False)

# 按照年龄区间拆分数据子集
age_groups = X.groupby('age_group')
for name, group in age_groups:
    print(f"年龄区间: {name}")
    print(group)


58    429
66    422
65    407
73    385
57    385
68    317
72    310
59    299
75    286
67    283
74    271
55    267
49    256
62    236
78    168
71    165
63    156
60    156
61    150
76    144
85    142
56    140
36    101
Name: age, dtype: int64
年龄区间: 0-49
      age  test_time  Jitter(%)  Jitter(Abs)  Jitter:RAP  Jitter:PPQ5  \
4295   36     11.477    0.00364     0.000019     0.00191      0.00182   
4296   36     17.447    0.00217     0.000012     0.00090      0.00106   
4297   36     24.419    0.00244     0.000011     0.00115      0.00122   
4298   36     31.404    0.00432     0.000024     0.00193      0.00208   
4299   36     38.402    0.00371     0.000021     0.00152      0.00186   
...   ...        ...        ...          ...         ...          ...   
4391   36    115.610    0.00284     0.000015     0.00137      0.00136   
4392   36    122.510    0.00276     0.000015     0.00125      0.00122   
4393   36    136.440    0.00285     0.000016     0.00095      0.00117   
4394 

C:\Users\HUAWEI\AppData\Local\Temp/ipykernel_26848/2554164730.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['age_group'] = pd.cut(X['age'], bins=bins, labels=labels, right=False)


In [20]:
datasets = [group for name, group in age_groups]
# 为每个数据集定义一个变量
X1, X2, X3, X4, X5 = datasets

assert X.index.equals(y.index)

# 按照年龄区间拆分数据子集
age_groups = X.groupby('age_group')

# 为每个数据集定义一个变量
X1, X2, X3, X4, X5 = [group for name, group in age_groups]

# 使用X的索引来拆分y
y1, y2, y3, y4, y5 = [y.loc[X.index] for X in [X1, X2, X3, X4, X5]]



# 打印每个数据集的信息
print("X1:\n", X1)
print("X2:\n", X2)
print("X3:\n", X3)
print("X4:\n", X4)
print("X5:\n", X5)

X1:
       age  test_time  Jitter(%)  Jitter(Abs)  Jitter:RAP  Jitter:PPQ5  \
4295   36     11.477    0.00364     0.000019     0.00191      0.00182   
4296   36     17.447    0.00217     0.000012     0.00090      0.00106   
4297   36     24.419    0.00244     0.000011     0.00115      0.00122   
4298   36     31.404    0.00432     0.000024     0.00193      0.00208   
4299   36     38.402    0.00371     0.000021     0.00152      0.00186   
...   ...        ...        ...          ...         ...          ...   
4391   36    115.610    0.00284     0.000015     0.00137      0.00136   
4392   36    122.510    0.00276     0.000015     0.00125      0.00122   
4393   36    136.440    0.00285     0.000016     0.00095      0.00117   
4394   36    164.550    0.00429     0.000018     0.00184      0.00198   
4395   36    178.540    0.00263     0.000012     0.00108      0.00076   

      Jitter:DDP  Shimmer  Shimmer(dB)  Shimmer:APQ3  Shimmer:APQ5  \
4295     0.00574  0.01893        0.164       0.0

In [21]:
import numpy as np

In [27]:
X_1 = X1.drop([ 'age', 'sex', 'test_time','age_group'],axis=1).values
X_2 = X2.drop([ 'age', 'sex', 'test_time','age_group'],axis=1).values
X_3 = X3.drop([ 'age', 'sex', 'test_time','age_group'],axis=1).values
X_4 = X4.drop([ 'age', 'sex', 'test_time','age_group'],axis=1).values
X_5 = X5.drop([ 'age', 'sex', 'test_time','age_group'],axis=1).values
y1 =y1.values
y2 =y2.values
y3 =y3.values
y4 =y4.values
y5 =y5.values

In [32]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

torch.manual_seed(0)

# 将数据集转换为PyTorch张量
X_train_tensor = torch.FloatTensor(np.concatenate([X_2, X_3, X_4], axis=0))
y_train_tensor = torch.FloatTensor(np.concatenate([y2, y3, y4], axis=0).reshape(-1,1))  
X_test1_tensor = torch.FloatTensor(X_1)
y_test1_tensor = torch.FloatTensor(y1.reshape(-1,1))
X_test2_tensor = torch.FloatTensor(X_5)
y_test2_tensor = torch.FloatTensor(y5.reshape(-1,1))

# 创建DataLoader
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test1_dataset = TensorDataset(X_test1_tensor, y_test1_tensor)
test2_dataset = TensorDataset(X_test2_tensor, y_test2_tensor)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test1_loader = DataLoader(test1_dataset, batch_size=32, shuffle=False)
test2_loader = DataLoader(test2_dataset, batch_size=32, shuffle=False)

# 定义神经网络模型
class SimpleNN(nn.Module):
    def __init__(self, input_dim):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_dim, 64)
        self.relu1 = nn.ReLU()
        self.fc2 = nn.Linear(64, 32)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(32, 1)

    def forward(self, x):
        x = self.relu1(self.fc1(x))
        x = self.relu2(self.fc2(x))
        x = self.fc3(x)
        return x

# 实例化模型、损失函数和优化器
model = SimpleNN(X_train_tensor.shape[1])
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# 训练神经网络
epochs = 10
for epoch in range(epochs):
    model.train()
    for inputs, targets in train_loader:
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()

# 评估模型
def evaluate_model(model, X_test, y_test):
    model.eval()
    with torch.no_grad():
        y_pred_tensor = model(X_test)
        y_pred = y_pred_tensor.numpy()
        rmse = mean_squared_error(y_test, y_pred, squared=False)
        return rmse

rmse1 = evaluate_model(model, X_test1_tensor, y_test1_tensor)
print(f'Root Mean Squared Error on the first test set: {rmse1}')

rmse2 = evaluate_model(model, X_test2_tensor, y_test2_tensor)
print(f'Root Mean Squared Error on the second test set: {rmse2}')


Root Mean Squared Error on the first test set: 10.517960548400879
Root Mean Squared Error on the second test set: 4.362770080566406


In [34]:
# 在X2，X3，X4上分别训练一个模型
models = []
for X_train, y_train in [(X_2, y2), (X_3, y3), (X_4, y4)]:
    model = SimpleNN(X_train.shape[1])
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    train_dataset = TensorDataset(torch.FloatTensor(X_train), torch.FloatTensor(y_train))
    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
    for epoch in range(epochs):
        model.train()
        for inputs, targets in train_loader:
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs.view(-1), targets)
            loss.backward()
            optimizer.step()
    models.append(model)




In [121]:
import numpy as np

# 初始化一个3*3的矩阵
matrix = np.zeros((3, 3))

# 对于每一个测试数据
for x in X_5:
    # 计算每个模型的输出
    outputs = [model(torch.FloatTensor(x)).detach().numpy() for model in models]
    # 对于每一对模型
    for i in range(3):
        for j in range(3):
            # 计算f_i(x)*f_j(x)
            matrix[i, j] += outputs[i] * outputs[j]

# 求平均
matrix /= len(X_5)
print(matrix)

[[290.43150308 328.34185189 430.13160211]
 [328.34185189 372.8737621  484.92583627]
 [430.13160211 484.92583627 638.13682879]]


In [159]:
import cvxpy as cp
import numpy as np

# 假设我们有一个3x3的正定矩阵Gamma
Gamma = np.array(matrix)

# 定义优化变量
q = cp.Variable(3)

q_sou = (len(X_2)/(len(X_2)+len(X_3)+len(X_4)),len(X_3)/(len(X_2)+len(X_3)+len(X_4)),len(X_4)/(len(X_2)+len(X_3)+len(X_4)))
epsilon = 0.5
# 定义优化问题
objective = cp.Minimize(cp.quad_form(q, Gamma))
constraints = [cp.sum(q) == 1, q >= 0,
               cp.norm(q - q_sou) <= epsilon]  
prob = cp.Problem(objective, constraints)

# 求解优化问题
result = prob.solve()

# 输出结果
print("最优值: ", result)
print("最优解: ", q.value)

最优值:  313.62246592291206
最优解:  [7.01895023e-01 2.98104976e-01 2.92281836e-10]


In [167]:
# 定义凸线性组合的权重
tau = 1*result
weights = tau/result * q.value

# 对X1和X5进行预测
for X_test, y_test in [(X_5, y5)]:
    X_test_tensor = torch.FloatTensor(X_test)
    y_test_tensor = torch.FloatTensor(y_test)
    preds = [model(X_test_tensor).detach().numpy() for model in models]
    # 计算凸线性组合
    y_pred = sum(w * pred for w, pred in zip(weights, preds))
    # 计算RMSE
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    print(f'Root Mean Squared Error on the test set: {rmse}')

Root Mean Squared Error on the test set: 1.5744479734523187
